name: 'Build'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'Build binary'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build binary'
        run: cargo build --release --target=x86_64-unknown-linux-gnu

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: getrec-recorder-x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/sandbox-rust-ci
