name: 'Release'

on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Echo'
        shell: bash
        run: echo hello
